[tools]
# languages
ruby = "latest"
# crystal = "latest"
# php = "latest"
# pnpm = "latest"
# python = "3.11"
zig = "latest"
lua = "latest"
python = "latest"

# utilities
hub = "latest"
eza = "latest"
usage = "latest"
jj = "latest"

[env]
RUBY_YJIT_ENABLE = "1"


[settings]
idiomatic_version_file_enable_tools = ["ruby"]
